### ISSUE TITLE
Hubot can't connect to Rocket Chat

### ISSUE THREAD

**Issue by Muffo** [RocketChat/hubot-rocketchat#100]
I am testing Rocket Chat for the first time and I am following [this guide to Deploy with Docker](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker)

I have started Rocket Chat successfully and I am now trying to enable the Hubot.
I have created a user called bot and I have modified the file **docker-compose.yml** with the updated login information.

Here is my file:

```
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=localhost:3000
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_ROOM=''
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=hubot
    # - RESPOND_TO_DM=true
    #- ROCKETCHAT_AUTH=password
    - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
```

I have started the container with Hubot but it does not seem to respond to the command within Rocket Chat.
I am not sure what is the expected output, but it seems that he can't connect to localhost:3000 which is the URL I use to open Rocket Chat.

```
> docker-compose up hubot   
Recreating rocketchat_mongo_1...
Recreating rocketchat_rocketchat_1...
Recreating rocketchat_hubot_1...
Attaching to rocketchat_hubot_1
hubot_1 | hubot-help@0.1.3 node_modules/hubot-help
hubot_1 | 
hubot_1 | hubot-diagnostics@0.0.1 node_modules/hubot-diagnostics
hubot_1 | 
hubot_1 | hubot-links@0.0.1 node_modules/hubot-links
hubot_1 | 
hubot_1 | hubot-seen@0.2.3 node_modules/hubot-seen
hubot_1 | ├── timeago@0.1.0
hubot_1 | └── coffee-script@1.6.3
hubot_1 | [Sat Feb 20 2016 16:37:18 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
hubot_1 | [Sat Feb 20 2016 16:37:18 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
hubot_1 | [Sat Feb 20 2016 16:37:18 GMT+0000 (UTC)] INFO Connecting To: localhost:3000
```

Do you have any suggestion?

Thanks!
Andrea
