### ISSUE TITLE
Hubot Brain set/get Does Not Persist Between Scripts

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/hubot-rocketchat#112]
I have a script that sets a userId `robot.brain.set('userId', body.data.userId)` to the brain on start up but when I try to access that value from a different script `robot.brain.get('userId')` I receive a `null`. I can only get the value within the same script.

Is this the intended behavior? I'm looking for a way to set a key/value of userId and auth token after making an http call to the Rocket.Chat API so I can make calls to list room and send messages using the token between different scripts so I only have to login once hitting `/api/login`

**Comment by geekgonecrazy** [comment]
@richardwlu we don't really control anything with the hubot brain.  That's all hubot specific.  I believe to persist though you need to hook up something like redis for the brain to store in.

**Comment by lucasvanhalst** [comment]
You can use the MongoDB database that's already used for Rocket.Chat for this, using this plugin: https://www.npmjs.com/package/hubot-mongodb-brain
Just add `hubot-mongodb-brain` to your `EXTERNAL_SCRIPTS` list in the config and you should be good.

**Comment by geekgonecrazy** [comment]
@lucasvanhalst that sounds like a great solution!  Thanks for sharing!

**Comment by timkinnane** [comment]
I'm trying to get the approach suggested by @lucasvanhalst working. Currently getting connection errors in development using mongo localhost. I'm guessing because the suggested script tries to start its own instance of Mongo, but the ports are in use already by Rocket.chat or it needs further config to connect to the Rocket.chat mongo. If anyone has got this working, please post solutions here, because the hubot-mongodb-brain package is not Rocket.chat specific and is pretty light on docs.

**Comment by lucasvanhalst** [comment]
@timkinnane 
using docker-compose your docker-compose.yml would look look this
```
mongo:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128
hubot:
  image: rocketchat/hubot-rocketchat:latest
  environment:
    - ROCKETCHAT_URL=https://hostname.com
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=<password>
    - LISTEN_ON_ALL_PUBLIC=true
    - RESPOND_TO_DM=true
    - BOT_NAME=bot
    - MONGODB_URL=mongodb://mongo/hubot-brain
    - EXTERNAL_SCRIPTS=hubot-mongodb-brain,hubot-help,hubot-seen,hubot-diagnostics

```
