### ISSUE TITLE
Message received twice when rocket chat server restarts

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/hubot-rocketchat#141]
When you restart/update your rocketchat server while hubot is running, messages will be received twice.
If you restart it again, they will be received 3 times and so on... 
This makes it lag really bad and to fix it you have to restart hubot each time you restart rocketchat.
It would be nice if this could be fixed so you don't have to do that every time

**Comment by geekgonecrazy** [comment]
@lucasvanhalst if you're running 0.37.0 of Rocket.Chat or higher... could you give the newest version of the adapter a try and see if this still happens to you?

**Comment by lucasvanhalst** [comment]
@geekgonecrazy Something must've gone wrong with building the latest version https://hub.docker.com/r/rocketchat/hubot-rocketchat/builds/
but I will give 1.0.2 a shot

**Comment by lucasvanhalst** [comment]
Can confirm this is still occurring with version 1.0.2
```
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Subscribing to Room: __my_messages__
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Successfully subscribed to messages
hubot         | [Wed Aug 24 2016 17:06:46 GMT+0000 (UTC)] INFO Setting up reactive message list...
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message receive callback id er4ALpnJLD2NrEHht ts Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO [Incoming] Lvh: bot ping
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message sent to hubot brain.
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message receive callback id er4ALpnJLD2NrEHht ts Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO [Incoming] Lvh: bot ping
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Sending Message To Room: GENERAL
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
hubot         | [Wed Aug 24 2016 17:07:01 GMT+0000 (UTC)] INFO Message received with ID id
```

It does not send the message twice (if it is a command that triggers something), but it is received twice.

**Comment by geekgonecrazy** [comment]
Thanks for pointing out that v1.0.3 was missing.  I've pushed and corrected that.

I need to figure how to replicate this so we can determine what's going on.

**Comment by lucasvanhalst** [comment]
@geekgonecrazy 
hmm this got worse, now I had my bot receiving every message 9 times, but I didn't restart either rocketchat or the bot in about a week, so it must be something else.

**Comment by lucasvanhalst** [comment]
This is still happening. I've noticed you don't even have to restart the server for it to receive messages multiple times, at this moment my bot was receiving every message 3 times after being up for  about 4 days.

**Comment by geekgonecrazy** [comment]
@lucasvanhalst I have a bot instance that has been running for several months, even with upgrades and haven't ran into this.  Can you give me a bit more info on your full setup so we can try and narrow down a way to reproduce this?

**Comment by lucasvanhalst** [comment]
I can give you part of my docker-compose file:
```yaml
hubot:
  image: rocketchat/hubot-rocketchat:latest
  container_name: hubot
  environment:
    - ROCKETCHAT_URL=https://example.com
    - ROCKETCHAT_ROOM= GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=********
    - LISTEN_ON_ALL_PUBLIC=true
    - RESPOND_TO_DM=true
    - BOT_NAME=bot
    - RESPOND_TO_EDITED=true
    - MONGODB_URL=mongodb://mongo/hubot-brain
    - EXTERNAL_SCRIPTS=hubot-mongodb-brain,hubot-help,hubot-seen,hubot-diagnostics,hubot-strawpoll,hubot-youtube,hubot-tell,hubot-bro,hubot-reaction,hubot-loudbot,hubot-shipit,hubot-react-fork,hubot-fliptable,hubot-cleverbot,hubot-response,hubot-praise,hubot-thank-you,hubot-insulter,hubot-isup,hubot-geo,hubot-reminders,hubot-insanedomains,hubot-currency,hubot-image-linker
  links:
    - mongo:mongo
  ports:
    - 3001:8080
  volumes:
    - ./data/responses:/home/hubot/responses
```

Perhaps it has something to do with RESPOND_TO_EDITED now that I think of it.
