### ISSUE TITLE
Tell hubot in docker to use the config/scripts situated somewhere else

### ISSUE THREAD

**Issue by VonKavalier** [RocketChat/hubot-rocketchat#173]
Hi,

I got a hubot folder, containing everything for hubot to work like I want (which means the `package.json` and all the scripts I want it to use) but not in the docker, and I was wondering if there is a way to "symlink" both docker folder and the one in my /home in order to use all the scripts by the hubot situated in the docker.

I'm not very good with docker, but in the rocket.chat folder that I use to start Rocket.Chat (via the `docker-compose.yml`) I see a `volumes` statement that might do what I need. I configured it like that for the hubot part : 

   ```
hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat:v1.0.1
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=''
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=hubot
    - ROCKETCHAT_PASSWORD=hubot
    - BOT_NAME=hubot
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  links:
    - rocketchat:rocketchat
  volumes:
    - ./:/home/osaxis/depot_git/rocketchat/myhubot/
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:3001
```

Well that doesn't work but I wasn't expecting much. Do you have any idea if it's possible ? And if yes, how ?
