### ISSUE TITLE
Usage with docker-compose

### ISSUE THREAD

**Issue by OEvgeny** [RocketChat/hubot-rocketchat#66]
Hi. I'm trying to setup `rocketchat/hubot-rocketchat` and `rocketchat/rocket.chat` to work together with docker-compose. My `docker-compose.yml`:
```yml
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=http://localhost:8818
  links:
    - db:db
  ports:
    - 8818:3000

hubot:
  image: rocketchat/hubot-rocketchat
  links:
    - rocketchat:rocketchat
  environment:
   -  ROCKETCHAT_URL=http://rocketchat:3000
   -  ROCKETCHAT_ROOM=GENERAL
   -  ROCKETCHAT_USER=bot
   -  ROCKETCHAT_PASSWORD=bot
   -  BOT_NAME=bot
   -  EXTERNAL_SCRIPTS=hubot-pugme,hubot-help
```

But it seem to not work for me. hubot container shows me only:
```
hubot_1      | hubot-help@0.1.2 node_modules/hubot-help
hubot_1      | 
hubot_1      | hubot-pugme@0.1.0 node_modules/hubot-pugme
...
hubot_1      | [Sat Oct 31 2015 13:40:22 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
hubot_1      | [Sat Oct 31 2015 13:40:22 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
hubot_1      | [Sat Oct 31 2015 13:40:22 GMT+0000 (UTC)] INFO Connecting To: http://rocketchat:3000
```
I also tried to run boot service from shell (using `docker-compose.yml` listed before):
```
$ docker-compose run --service-ports hubot bash
hubot@6924d55fb96d:~$ bin/hubot -n $BOT_NAME -a rocketchat
```
It shows all the same:
```
[Sat Oct 31 2015 14:08:28 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Sat Oct 31 2015 14:08:28 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
[Sat Oct 31 2015 14:08:28 GMT+0000 (UTC)] INFO Connecting To: http://rocketchat:3000
```

Pinging `rocketchat` and `curl http://rocketchat:3000` from hubot container works well.

Also I created bot user with the same password via user registration form. 

Note: all other chat functions and chat itself works just fine. Only hubot is not working. I don't see any message from it and new commands are not appear after I type `/`

What am I doing wrong?..
