### ISSUE TITLE
Custom scripts

### ISSUE THREAD

**Issue by miscs** [RocketChat/hubot-rocketchat#73]
Hi all,

I managed to get rocket.chat with hubby running using docker. Works great!
But now I don't know how to add custom hubot scripts (probably due to my missing docker knowledge).

My docker-compose.ml looks like this:

```
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=192.168.1.51:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=spryBot
    - ROCKETCHAT_PASSWORD=r3Lz9n6Aj4a5d1w208O
    - BOT_NAME=sprybot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
  links:
    - rocketchat:rocketchat
```

But I don´t get how I include something like this
```
-v $PWD/scripts:/home/hubot/scripts
```

into my docker-compose.ml. It would be the best to have the directory for custom scripts outside the docker, or am I wrong?

Thanks for any help!!!
Steve
