### ISSUE TITLE
hubot inactive after update to "version": "0.13.0",

### ISSUE THREAD

**Issue by miscs** [RocketChat/hubot-rocketchat#90]
Hi all,

I just updated to "version": "0.13.0" and now hubot is offline (docker install). I also restarted everything. Logs shows

```
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: sprybot
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Connecting To: 192.168.1.51:3000
```

An nothing happens :( Any clues how I can debug a little bit further. I can´t see anything in rocket.chat logs itself....

Thanks for any hints!

**Comment by miscs** [comment]
if it matters - the docker-compose.yml which I use for hubot:
```
hubot:
  image: rocketchat/hubot-rocketchat
  volumes:
    - $PWD/scripts:/var/www/hubotscripts
    - $PWD/scripts:/var/www/hubotscripts/node_modules
  environment:
    - ROCKETCHAT_URL=192.168.1.51:3000
    - ROCKETCHAT_ROOM=GENERAL
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=botUser
    - ROCKETCHAT_PASSWORD=lknsdlknsdlfkn3
    - BOT_NAME=hubot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings,hubot-standup-alarm,hubot-giphy-gifme
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080
```

**Comment by Sing-Li** [comment]
It may not be the update.   How did you start the server?   

Can you point a browser to:

```
http://192.168.1.51:3000/
```

...and see a login screen?

**Comment by miscs** [comment]
Hi @Sing-Li thanks for your reply!

Going to `http://192.168.1.51:3000/` is showing the rocket.chat login (-> `http://192.168.1.51:3000/home`)

I´m starting the server using my docker-compose.yml file (like before the update):

```
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.mydomain.com
  links:
    - db:db
  ports:
    - 3000:3000

hubot:
  image: rocketchat/hubot-rocketchat
  volumes:
    - $PWD/scripts:/var/www/hubotscripts
    - $PWD/scripts:/var/www/hubotscripts/node_modules
  environment:
    - ROCKETCHAT_URL=192.168.1.51:3000
    - ROCKETCHAT_ROOM=GENERAL
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=botuser
    - ROCKETCHAT_PASSWORD=sdfs92i3nfd
    - BOT_NAME=hubot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings,hubot-standup-alarm,hubot-giphy-gifme
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080
```

And all containers are running:
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                    NAMES
6a1a0a5a3e51        rocketchat/hubot-rocketchat     "/bin/sh -c 'node -e "   14 hours ago        Up 14 hours         0.0.0.0:3001->8080/tcp   rocketchat_hubot_1
1dc8b47f7b75        rocketchat/rocket.chat:latest   "node main.js"           15 hours ago        Up 14 hours         0.0.0.0:3000->3000/tcp   rocketchat_rocketchat_1
75daf1637fb8        mongo                           "/entrypoint.sh mongo"   4 weeks ago         Up 14 hours         27017/tcp                rocketchat_db_1
```

**Comment by Sing-Li** [comment]
The actual LOG is *very important* for diagnosis

* notice the name `sprybot` in the log - it is not in your config
* we need to know the *EXACT* content of your config + log (-password), especially the LAST 10 lines, please copy it here

```
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: sprybot
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Connecting To: 192.168.1.51:3000
```

**Comment by miscs** [comment]
@Sing-Li Sorry, I just played a bit with the configuration to check if naming changes anything and copied the logs from different test-runs :( 
This is my original configuration which worked before my update (changed only ROOT_URL and ROCKETCHAT_PASSWORD):

```
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.myurl.com
  links:
    - db:db
  ports:
    - 3000:3000

hubot:
  image: rocketchat/hubot-rocketchat
  volumes:
    - $PWD/scripts:/var/www/hubotscripts
    - $PWD/scripts:/var/www/hubotscripts/node_modules
  environment:
    - ROCKETCHAT_URL=192.168.1.51:3000
    - ROCKETCHAT_ROOM=GENERAL
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=spryBot
    - ROCKETCHAT_PASSWORD=12221
    - BOT_NAME=sprybot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings,hubot-standup-alarm,hubot-giphy-gifme
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080
```

Complete log from rocketchat/hubot-rocketchat container (docker logs 6a1a0a5a3e51)

```
hubot-help@0.1.3 node_modules/hubot-help

hubot-links@0.0.1 node_modules/hubot-links

hubot-giphy-gifme@0.1.4 node_modules/hubot-giphy-gifme
└── coffee-script@1.6.3

hubot-greetings@1.0.0 node_modules/hubot-greetings
└── coffee-script@1.6.3

hubot-seen@0.2.3 node_modules/hubot-seen
├── timeago@0.1.0
└── coffee-script@1.6.3

hubot-standup-alarm@0.0.7 node_modules/hubot-standup-alarm
├── underscore@1.8.3
└── cron@1.0.9 (moment-timezone@0.3.1)
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Starting Rocketchat adapter...
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: sprybot
[Mon Jan 11 2016 17:54:08 GMT+0000 (UTC)] INFO Connecting To: 192.168.1.51:3000

```
